/**
 * @module modules/commands/util/clip.js
 * @description Copy session history to clipboard as formatted Markdown.
 * 
 * @connections
 * - Imports: 
 *     - ANSI from '../../formatter.js'
 *     - getHistory, getNotes from '../../state.js'
 *     - ContextManager from '../../context.js'
 * - Exports: cmdClip
 * - Layer: Command Layer (Util) - Terminal utilities and internal tools.
 */

import { ANSI } from "../../formatter.js";
import { getHistory, getNotes } from "../../state.js";
import { ContextManager } from "../../context.js";

// ===================================================================
//  clip — Copy session history to clipboard as Markdown
//
//  Syntax:
//    clip              → Copy full session
//    clip <domain>     → Copy only entries for that domain
// ===================================================================

/**
 * Strip ANSI escape codes from a string.
 */
function stripAnsi(str) {
    return str.replace(/\x1b\[[0-9;]*m/g, "");
}

/**
 * Format a single history entry as a Markdown block.
 */
function formatEntry(entry) {
    const time = entry.timestamp
        ? new Date(entry.timestamp).toLocaleTimeString("en-US", { hour12: false })
        : "??:??:??";
    const cmd = stripAnsi(entry.command || "").trim();
    const rawOutput = stripAnsi(entry.output || "").trim();

    // Collapse excessive blank lines in output
    const output = rawOutput.replace(/\n{3,}/g, "\n\n");

    let block = `### \`❯ ${cmd}\`\n`;
    block += `_${time}_\n\n`;
    block += "```\n";
    block += output + "\n";
    block += "```\n";
    return block;
}

export async function cmdClip(args) {
    const history = getHistory();

    if (history.length === 0) {
        return `${ANSI.yellow}No commands in session to copy.${ANSI.reset}\n${ANSI.dim}Run some commands first, then try again.${ANSI.reset}`;
    }

    // Resolve filter: "clip target" uses the active target domain
    let filterDomain = args[0]?.toLowerCase();
    if (filterDomain === "target") {
        const currentTarget = ContextManager.getDomain();
        if (!currentTarget) {
            return `${ANSI.yellow}No active target set.${ANSI.reset}\n${ANSI.dim}Use ${ANSI.white}clip${ANSI.dim} for the full session, or ${ANSI.white}clip <domain>${ANSI.dim} to filter manually.${ANSI.reset}`;
        }
        filterDomain = currentTarget.toLowerCase();
    }
    let filtered = history;

    if (filterDomain) {
        filtered = history.filter(entry => {
            const cmd = stripAnsi(entry.command || "").toLowerCase();
            const output = stripAnsi(entry.output || "").toLowerCase();
            return cmd.includes(filterDomain) || output.includes(filterDomain);
        });

        if (filtered.length === 0) {
            return `${ANSI.yellow}No entries found for '${filterDomain}'.${ANSI.reset}\n${ANSI.dim}Use ${ANSI.white}clip${ANSI.dim} without arguments to copy the full session.${ANSI.reset}`;
        }
    }

    // Build Markdown document
    const activeDomain = ContextManager.getDomain() || "Unknown";
    const now = new Date();
    const dateStr = now.toISOString().split("T")[0];
    const timeStr = now.toLocaleTimeString("en-US", { hour12: false });

    let md = `# WhatHappened — Session Report\n\n`;
    md += `| Field | Value |\n`;
    md += `|-------|-------|\n`;
    md += `| **Date** | ${dateStr} |\n`;
    md += `| **Time** | ${timeStr} |\n`;
    md += `| **Target** | \`${activeDomain}\` |\n`;

    if (filterDomain) {
        md += `| **Filter** | \`${filterDomain}\` |\n`;
    }

    md += `| **Commands** | ${filtered.length} |\n`;
    md += `\n---\n\n`;

    // Session notes
    const notes = getNotes();
    if (notes.length > 0) {
        md += `## Notes\n\n`;
        for (const note of notes) {
            const t = new Date(note.time).toLocaleTimeString("en-US", { hour12: false });
            md += `- **${t}** — ${note.text}\n`;
        }
        md += `\n---\n\n`;
    }

    // Command entries
    md += `## Commands\n\n`;
    for (const entry of filtered) {
        md += formatEntry(entry) + "\n";
    }

    md += `\n\n---\n`;
    md += `> Generated by [WhatHappened](https://github.com/netssv/whathappend)\n`;
    md += `> ${new Date().toISOString()}`;

    // Copy to clipboard
    try {
        await navigator.clipboard.writeText(md);
    } catch (_) {
        return `${ANSI.red}[ERROR] Clipboard write failed.${ANSI.reset}\n${ANSI.dim}Browser may have denied clipboard access.${ANSI.reset}`;
    }

    const sizeKB = (new TextEncoder().encode(md).length / 1024).toFixed(1);
    let out = `${ANSI.green}✓ Copied to clipboard${ANSI.reset}`;
    if (filterDomain) {
        out += ` ${ANSI.dim}(filtered: ${filterDomain})${ANSI.reset}`;
    }
    out += `\n  ${ANSI.dim}${filtered.length} commands | ${sizeKB} KB | Markdown format${ANSI.reset}`;
    out += `\n  ${ANSI.dim}Paste into any ticket, doc, or chat.${ANSI.reset}`;
    return out;
}
